#! /bin/sh


md_with_extensions=markdown
md_with_extensions="$md_with_extensions+all_symbols_escapable"
md_with_extensions="$md_with_extensions+auto_identifiers"
# md_with_extensions="$md_with_extensions+implicit_figures"
md_with_extensions="$md_with_extensions+fenced_divs"
md_with_extensions="$md_with_extensions+fancy_lists"

# --include-in-header="./header.tex" \
pandoc \
    -t beamer \
    -f "$md_with_extensions" \
    --table-of-contents \
    --shift-heading-level-by=0 \
    --number-section \
    --pdf-engine=lualatex \
    --slide-level=2 \
    "$1" \
    -o "./output/${1%.*}.pdf" &

pandoc_pid=$!
echo Started Pandoc

start_time=$(date +%s)
while kill -0 $pandoc_pid &>/dev/null; do
    sleep 2
    printf 'Waiting for %s...\r' "$(date --date="@$(expr "$(date +%s)" - $start_time)" "+%M:%S")"
done
echo

if [ "$?" -ne 0 ]; then
    >&2 printf '%s\n    %s\n\nRun (this program is bundled with latex):\n\t%s\n\n%s' \
        "Hi me! If you're getting: " \
        "Missing character: There is no <char> (U+ABCD) in font <font-name>" \
        "albatross U+ABCD" \
        "to get a list of system fonts which have that character in them."
    notify-send \
        --urgency critical \
        -t 3000 \
        "mkbeamer @ $(realpath ${0%/*})" \
        'Failed Miserably'
else
    notify-send \
        -t 3000 \
        "mkbeamer @ $(realpath ${0%/*})" \
        'Done'
fi


